# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wVNeifI5B9So5_R3306r3hUIOHqojO0k
"""

a = '''My life's been magic, seems fantastic
I used to have a hole in the wall with a mattress
Funny when you want it, suddenly you have it
You find out that your gold's just plastic
Every day, every night
I've been thinkin' back on you and I
Every day, every night
I worked my whole life
Just to get right, just to be like
"Look at me, I'm never coming down"
I worked my whole life
Just to get high, just to realize
Everything I need is on the
Everything I need is on the ground
On the ground
Everything I need is on the ground
(Nah, but they don't hear me though)
(Yeah, what goes up must come down)
(Nah, but they don't hear me though)
(You're runnin' out of time)
My world's been hectic, seems electric
But I've been waking up with your voice in my head
And I'm tryna send a message and let you know that
Every single minute I'm without you, I regret it
Every day, every night
I've been thinkin' back on you and I
Every day, every night
I worked my whole life
Just to get right, just to be like
"Look at me, I'm never coming down"
I worked my whole life
Just to get high, just to realize
Everything I need is on the
Everything I need is on the ground
On the ground
Everything I need is on the ground
(Nah, but they don't hear me though)
(Yeah, what goes up must come down)
(Nah, but they don't hear me though)
(You're runnin' out of time)
I'm way up in the clouds
And they say I've made it now
But I figured it out
Everything I need is on the ground (yeah, yeah)
Just drove by your house (just drove by your house)
So far from you now (so far from you now)
But I figured it out
Everything I need is on the
Everything I need is on the ground
On the ground
Everything I need is on the ground
(Nah, but they don't hear me though)
On the ground
(Nah, but they don't hear me though)
Everything I need is on the ground'''

b = a.replace('\n', ' ')
b = b.replace('(', ' ')
b = b.replace(')', ' ')
b = b.replace('  ', ' ')
c = b.split(' ')
#print(c)


d = dict()
#e = list[]
#f = list 

words = c
print(d)
for word in words :
    if word in d :
        d[word] = d[word] + 1
    else :
        d[word] = 1

print(d)

a = [["A",1],["a",2]]
print(a)
p = dict(a)
print(p)
p[5]=2
print(p)

a = '''My life's been magic, seems fantastic
I used to have a hole in the wall with a mattress
Funny when you want it, suddenly you have it
You find out that your gold's just plastic
Every day, every night
I've been thinkin' back on you and I
Every day, every night
I worked my whole life
Just to get right, just to be like
"Look at me, I'm never coming down"
I worked my whole life
Just to get high, just to realize
Everything I need is on the
Everything I need is on the ground
On the ground
Everything I need is on the ground
(Nah, but they don't hear me though)
(Yeah, what goes up must come down)
(Nah, but they don't hear me though)
(You're runnin' out of time)
My world's been hectic, seems electric
But I've been waking up with your voice in my head
And I'm tryna send a message and let you know that
Every single minute I'm without you, I regret it
Every day, every night
I've been thinkin' back on you and I
Every day, every night
I worked my whole life
Just to get right, just to be like
"Look at me, I'm never coming down"
I worked my whole life
Just to get high, just to realize
Everything I need is on the
Everything I need is on the ground
On the ground
Everything I need is on the ground
(Nah, but they don't hear me though)
(Yeah, what goes up must come down)
(Nah, but they don't hear me though)
(You're runnin' out of time)
I'm way up in the clouds
And they say I've made it now
But I figured it out
Everything I need is on the ground (yeah, yeah)
Just drove by your house (just drove by your house)
So far from you now (so far from you now)
But I figured it out
Everything I need is on the
Everything I need is on the ground
On the ground
Everything I need is on the ground
(Nah, but they don't hear me though)
On the ground
(Nah, but they don't hear me though)
Everything I need is on the ground'''

b = a.replace('\n', ' ')
b = b.replace('(', ' ')
b = b.replace(')', ' ')
b = b.replace('  ', ' ')
c = b.split(' ')
#print(c)

la = [] # 단어가 들어갈 리스트
ca = [] # la 단어에 대한 카운트 리스트
max = 0

for i in c :
    if i in la :
        continue
    if (max < c.count(i)) :
        max = c.count(i)
    la.append(i)
    ca.append(c.count(i))
    #print("%10s는 %10s번 나온다" % (i, c.count(i)))
ac = sorted(ca)
ac = reversed(ac)
ac = list(ac)
#print("%s번 출현이 가장 많이 출현된 숫자이다." % max)

print(la)
print(ac)